model:
  model: latest_model
  tokenizer: latest_model
  dataset_folder: dataset
  exclude_file: null
  entities:
  - working_type
  - shift_type
  intents:
  - WorkTimesBreaches
  - WorkingTimeBreachDiscipline
  - HolidaysOff
  - AnnualLeaveApplicationProcess
  - SetWorkingType
  - TemporarySetWorkingType
  - WorkingHours
  - WorkingDay
  - BreakTime
  - Pregnant
  - AttendanceRecord
  - SelectShiftType
  - LaborContract
  - Recruitment
  - SickLeave
  - UnpaidLeave
  - PaidLeaveForFamilyEvent
  - UnusedAnnualLeave
  - RegulatedAnnualLeave
  - rating
  - greet
  - goodbye
  - affirm
  - deny
  device: cuda
  synonym:
    office hour: office hours
    office: office hours
    office hours: office hour
training:
  train_range: 0.95
  num_train_epochs: 100
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 500
  weight_decay: 0.01
  logging_dir: logs/
  early_stopping_patience: 10
  early_stopping_threshold: 0.0001
  output_dir: results/
util:
  intent_threshold: 0.7
  entities_threshold: 0.5
  ambiguous_threshold: 0.2
